### ISSUE TITLE
Question about the data augmentation.

### ISSUE THREAD

**Issue by JHR0717** [GT-SALT/MixText#10]
Hello,  I am following your work!
I have a question about the figure 2 in your paper.
Why the figure shows that you only augment the unlabel data ?
Looking forward your answer!

**Comment by jiaaoc** [comment]
We augment unlabeled data to perform consistency training. But the labeled data can be augmented as well. There is an option in the code that allow augmenting labeled data as well. You could refer to the codes for details.

**Comment by jiaaoc** [comment]
Please refer to `--train_aug` in train.py

**Comment by JHR0717** [comment]
Thank you for your reply! I haven't read the code sorry! 







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GT-SALT/MixText"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 中午11:12
收件人:&nbsp;"GT-SALT/MixText"<MixText@noreply.github.com&gt;;
抄送:&nbsp;"贾惠然"<756802073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GT-SALT/MixText] Question about the data augmentation. (#10)





 
We augment unlabeled data to perform consistency training. But the labeled data can be augmented as well. There is an option in the code that allow augmenting labeled data as well. You could refer to the codes for details.

**Comment by JHR0717** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GT-SALT/MixText"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 中午11:13
收件人:&nbsp;"GT-SALT/MixText"<MixText@noreply.github.com&gt;;
抄送:&nbsp;"贾惠然"<756802073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GT-SALT/MixText] Question about the data augmentation. (#10)





 
Please refer to --train_aug in train.py

**Comment by jiaaoc** [comment]
To use that option, you might need to make some additional modifications. We find empirically that the contribution of augmented labeled data is not that much.

**Comment by JHR0717** [comment]
Hummmm,&nbsp; It‘s interesting……
I thought data augmentation is used to solve the problem of sparse label data, so consider to augment the label data intuitively.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GT-SALT/MixText"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 中午11:16
收件人:&nbsp;"GT-SALT/MixText"<MixText@noreply.github.com&gt;;
抄送:&nbsp;"贾惠然"<756802073@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GT-SALT/MixText] Question about the data augmentation. (#10)





 
To use that option, you might need to make some additional modifications. We find empirically that the contribution of augmented labeled data is not that much.
