### ISSUE TITLE
A little question about  pre-processed Yahoo Answer dataset.

### ISSUE THREAD

**Issue by JeremySun1224** [GT-SALT/MixText#12]
hello @jiaaoc 😊
First of all, all my compliments to you and your team for the great results with this model.
I want to use it on my Chinese datasets, But I'm seeing that the first and second columns of the  **pre-processed Yahoo Answer dataset** you provided are labels. 

| label | label | content |
| ------ | ------ | ------ |
| 5 | 5 | why doesn't an optical mouse work on a glass table? ...... |
| 6 | 6 | what is the best off-road motorcycle trail ?...... |

Do I need to repeat the labels twice on my dataset?

**Comment by jiaaoc** [comment]
That's just about the format of datasets and the pre-processing codes about reading those data. You don't need to do that if you change the corresponding part in the codes.
