### ISSUE TITLE
Question about the back translations.

### ISSUE THREAD

**Issue by callmeYe** [GT-SALT/MixText#13]
Can I not do data augmentation on unlabelled data?

**Comment by jiaaoc** [comment]
We use back-translation to create paraphrases for unlabeled data and perform consistency training. You could use other ways to generate paraphrases.

**Comment by callmeYe** [comment]
So I have to create paraphrases, right? In addition, When I look at the code, I find that only the first 100,000 pieces of data in the data set have been back translated. Do I not need to perform back translation for all the datasets？

**Comment by jiaaoc** [comment]
It depends on the size of the unlabeled data you are going to use.  In this work, we used 100,000 unlabeled data, so we just did back translations on them, not the whole dataset.

**Comment by callmeYe** [comment]
Sorry, I'm still a little confused. 
When I test with:
`
python ./code/train.py --gpu 0,1 --n-labeled 10 \
--data-path ./data/yahoo_answers_csv/ --batch-size 2 --batch-size-u 4 --epochs 20 --val-iteration 1000 \
--lambda-u 1 --T 0.5 --alpha 16 --mix-layers-set 7 9 12 \
--lrmain 0.000005 --lrlast 0.0005
`
The number of unlabeled data per class seems to be 5,000. Do they add up to exactly 100,000?

**Comment by jiaaoc** [comment]
You could use up to 100,000

**Comment by jiaaoc** [comment]
10,000

**Comment by jiaaoc** [comment]
Anyway, the number of data you need to paraphrase only depends on the number of unlabeled data you are going to use.

**Comment by callmeYe** [comment]
Are they one-to-one correspondence？

**Comment by jiaaoc** [comment]
one unlabeled data could be associated with multiple paraphrases. Please refer to the paper/codes for details.
