### ISSUE TITLE
tcmalloc: large alloc 44581601280 bytes

### ISSUE THREAD

**Issue by JeremySun1224** [GT-SALT/MixText#15]
Hi @jiaaoc 
All my compliments to you and your team for the great results with this model.👍
When I run the following code on the Yahoo Answer dataset you provided on Colab (RAM=24G, Memory=16G)
`!python ./code/train.py --gpu 0 --n-labeled 10 --data-path ./data/yahoo_answers_csv/ --batch-size 4 --batch-size-u 8 --epochs 20 --val-iteration 1000 --lambda-u 1 --T 0.5 --alpha 16 --mix-layers-set 7 9 12 --lrmain 0.000005 --lrlast 0.0005`
get the error about tcmalloc：

“””
2020-11-24 14:11:01.275980: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
GPU num:  1
Whether mix:  True
Mix layers sets:  [7, 9, 12]
**tcmalloc: large alloc 44581601280 bytes** == 0x7f6ef822c000 @  0x7f7a28081001 0x7f7a25453765 0x7f7a254b7bb0 0x7f7a254badb8 0x7f7a254bb395 0x7f7a2555265d 0x50a4a5 0x50beb4 0x507be4 0x509900 0x50a2fd 0x50cc96 0x5095c8 0x50a2fd 0x50beb4 0x507be4 0x50ad03 0x634e72 0x634f27 0x6386df 0x639281 0x4b0dc0 0x7f7a27c7cbf7 0x5b259a
^C
“””
Does this error mean that more than 40G of memory is required to run the above code? If so, it is difficult to find such a machine.😢
Looking forward to your reply😊

**Comment by jiaaoc** [comment]
You could try (i) a smaller batch size, or (ii) use multiple GPUs as what was mentioned in the readme (e.g., four gpus).
