### ISSUE TITLE
I want to know what 102 means

### ISSUE THREAD

**Issue by callmeYe** [GT-SALT/MixText#16]
Sorry for disturbing you again. I tried to change the max_seq_len to 512, and change the BERT to Electra. but I'm not sure that 102 in this line of code needs to be changed

https://github.com/GT-SALT/MixText/blob/f17198d98e1bbb012d8e33cd26e228dd43bb4673/code/train.py#L313

**Comment by jiaaoc** [comment]
This is another way to mix two sequences.

For example: "I love math so much" and "He likes NLP" could be mixed to form "He likes NLP so much".

102 should be the special token id or a specific token id in BERT pre-trained model. Please check the corresponding token id if you change the pre-trained model.

**Comment by callmeYe** [comment]
Thanks! And then I need to change the number 256 to 512 in train.py, right? I have changed the max_seq_len to 512 in get_data function.  I'm not sure if I need to make the corresponding changes in mixtext.py

**Comment by jiaaoc** [comment]
You might want to check the pooling in the mixtext.py

**Comment by callmeYe** [comment]
Emmmm, You mean this code?
`self.pooler = BertPooler(config)`
I found that the parameter sent_size in train.py will be passed to the config.

**Comment by jiaaoc** [comment]
NVM, I mean if you are using max pooing to get the sentence representation, you might need to modify the window size.
