### ISSUE TITLE
About args.val-iterations.

### ISSUE THREAD

**Issue by ValkyriaLenneth** [GT-SALT/MixText#19]
Dear authors, I noticed that if val-iteration is always set to 1000 for batch size:4, batch size u:8, for each epoch only 4000 labeled data and 8000 unlabeled data is used. This is fine when num_labeled is 10 per class. How about num_labeled is 2500? Is args.val-iterations set to 1000 for every experiments? Thanks alot.

**Comment by jiaaoc** [comment]
1000 also works as long as there are more epochs. Or you could increase the val_iterations.
