### ISSUE TITLE
Unlabelled Data Formatting

### ISSUE THREAD

**Issue by RachitBansal** [GT-SALT/MixText#2]
Hey, 

I was trying to test your model for my custom data which contains both labelled and unlabelled sentences. Though I am not sure how I need to format, structure and keep my unlabelled data. 

I was able to run it successfully on the preprocessed Yahoo dataset but there were only labelled examples present in it as far as I could observe.

**Comment by jiaaoc** [comment]
The unlabeled data and labeled data is in the same format.

**Comment by jiaaoc** [comment]
Also, you can check the "back_translation" script and the provided pickle file to check the format.

**Comment by RachitBansal** [comment]
Thank you for your reply.

> The unlabeled data and labeled data is in the same format.

What goes for the labels in case of the unlabelled data? Or, is it just one column containing the sentences? 


> Also, you can check the "back_translation" script and the provided pickle file to check the format.

I checked the BT notebook but it seems to be taking the 'train.csv' file as the only input, which contains the labeled data only. 

If there is something I am misunderstanding, please let me know.

**Comment by jiaaoc** [comment]
We randomly sampled data from train.csv to form the unlabeled set.

**Comment by jiaaoc** [comment]
Also, you could check the read_data.py to check some details.

**Comment by RachitBansal** [comment]
Got it. Thanks a lot.
