### ISSUE TITLE
reproducing results for BERT baseline

### ISSUE THREAD

**Issue by Aha6988** [GT-SALT/MixText#20]
hello!
I tried to run the BERT baseline model that only uses labeled data with the command you provided:
python ./code/normal_train.py --gpu 0,1 --n-labeled 10 --data-path ./data/yahoo_answers_csv/ \
--batch-size 8 --epochs 20 

 but I get only 20% accuracy while in the paper is 56.2%. 
 is this exactly the configuration you used for training BERT model or something is missing in this command?

**Comment by jiaaoc** [comment]
Yes this is the exact configue. Could you check if you are using yahoo answers correctly? #1
