### ISSUE TITLE
About dataset construction

### ISSUE THREAD

**Issue by qiusg** [GT-SALT/MixText#22]
Hello, your work is excellent. Based on the construction of the dataset, I have a small question. After reading your code, I found that the unlabeled data is obtained by stratified sampling from the labeled data, so that the number of samples in the training set is balanced, but in real scenarios, we can't know the unlabeled data's label and then construct such a balanced train set. Can your method deal with such situation?

**Comment by jiaaoc** [comment]
Thanks for your interest in our work. Yes, our method can deal with the cases you mentioned.
