### ISSUE TITLE
Not using entropy minimization loss in the final model?

### ISSUE THREAD

**Issue by kkteru** [GT-SALT/MixText#28]
Hey @jiaaoc @diyiy,

A quick clarification question -- looks like the `lambda-u-hinge` parameter is always set to zero and also following the code, the hinge loss (entropy minimization loss, Sec 4.4 in the paper) is never added to the final loss in the MixText/TMix configuration of the code, i.e., line 353 is never executed.

Is that correct? Or am I missing something?

**Comment by jiaaoc** [comment]
The weight could be set to be 0.05/0.1/0.5
