### ISSUE TITLE
AttributeError: 'BertConfig' object has no attribute 'chunk_size_feed_forward'

### ISSUE THREAD

**Issue by dnnxl** [GT-SALT/MixText#30]
Hello, what version of transformers are you using in the code? Tried to run and instance the MixText model but got an error of no attribute  'chunk_size_feed_forward' when creating the layers.
```
model = MixText(n_labels, args['mix_option']).cuda()
```

And using 'bert-base-uncased' as pretrained model.

**Comment by TahaAslani** [comment]
I have the same issue.

**Comment by jiaaoc** [comment]
I used a pretty old version of transformers, which is pytorch_transformers. I think that should be the initial version of the current transformers package.
