### ISSUE TITLE
Few questions about the repository

### ISSUE THREAD

**Issue by JJumSSu** [GT-SALT/MixText#4]
Hello. I read & enjoyed your paper. I think this work(paper&repository) is a charm.
I have a few questions regarding your repository,

1. Is the baseline, i.e. UDA(Xie et al., 2019), tested from the implemented code?
If so, would you provide a way to run the UDA code?

2. As for the other dataset except the 'Yahoo', do I have to preprocess them as well? or just use the raw files from the google drive you uploaded?

I think your work is wonderful :)

Thank you.

**Comment by jiaaoc** [comment]
1. For the UDA baseline, you could check their implementation at https://github.com/google-research/uda. Or running MixText without using TMix/weighted average for simpler testing.

2. We only did some simple pre-processing for the Yahoo! Answer and uploaded the pre-processed files through the google drive (you can directly download the files and run our codes).  For the other dataset, you could directly download the original dataset and use the corresponding part for classifications (described in readme). You might need to run the back-translation codes to get the paraphrases in advance.
