### ISSUE TITLE
Missing Special Inputs for the BERT such as <CLS> or <SEP>

### ISSUE THREAD

**Issue by JJumSSu** [GT-SALT/MixText#5]
Hi, 

I'm currently working on your repository, and it seems that some special tokens for the BERT are missing. (e.g. <CLS> or <SEP>)

From my understanding, those special characters are not concatenated to the input text and are fed to the BERT model.

Is it right? Or am I missing it?

Thank you

**Comment by jiaaoc** [comment]
Yes, I did not concatenate the [CLS] and [SEP]. As it is not the key point for text classification. 

Also, as suggested in https://huggingface.co/transformers/model_doc/bert.html#bertmodel: 

> The output of [CLS] token is usually not a good summary of the semantic content of the input, you’re often better with averaging or pooling the sequence of hidden-states for the whole input sequence.

But you could try to add those tokens as well.

**Comment by JJumSSu** [comment]
Thank you! :)
