### ISSUE TITLE
Sequences too long for backtranslation

### ISSUE THREAD

**Issue by monkeysforever** [GT-SALT/MixText#6]
I was trying to use the backtranslation code with the IMDB polarity dataset. But the sequences are very long and fairseq is giving an error. How you handle such long sequences? Thanks for the code.

**Comment by jiaaoc** [comment]
What is the error? I did not do any pre-processing when doing the back-translation. But you could try setting a length limit, and only look at the last K words.

**Comment by monkeysforever** [comment]
![error](https://user-images.githubusercontent.com/13309365/89952178-6158ce80-dbf2-11ea-81a7-e41818afd14d.png)

**Comment by jiaaoc** [comment]
In that case, you might want to keep the last 1024 tokens in the sentence. But you could also change the max_positions in fairseq model as well.

**Comment by monkeysforever** [comment]
Thanks!
