### ISSUE TITLE
Access to Sampled Data?

### ISSUE THREAD

**Issue by NoviScl** [GT-SALT/MixText#7]
In the experiments you did down-sampling for the datasets (e.g., sample 10 labeled example per class). May I check if the sampled datasets are available for downloading? I'm asking this because if we do the sampling by ourselves, the difference in sampled data may cause the experiment results to be not directly comparable.

**Comment by jiaaoc** [comment]
If you could check the code, the random seed is fixed. So the sampled data is the same.
