### ISSUE TITLE
Reproducing UDA Results

### ISSUE THREAD

**Issue by timoschick** [GT-SALT/MixText#8]
Hi @diyiy @jiaaoc ,

just a quick question: Can I also use the code found in this repo to reproduce your UDA results reported in the paper? If so, how?

Thanks :)

**Comment by jiaaoc** [comment]
You could refer to this repo: https://github.com/GT-SALT/AAAI_CLF. In this repo, we provide a pytorch version of UDA with additional feature (you could refer to the paper for more details, but the basic framework is UDA)

**Comment by timoschick** [comment]
Thanks for the fast reply! Is this also the implementation that you have used for the MixText paper? (In other words, will I obtain the UDA results reported in the MixText paper using the https://github.com/GT-SALT/AAAI_CLF repo?)

**Comment by jiaaoc** [comment]
Yes, but you might need to remove several components.

**Comment by jiaaoc** [comment]
Another quick option is that you could remove the TMix in this repo to check the performance. That is close to UDA as well.

**Comment by timoschick** [comment]
Thanks again! It seems to me that TMix can be disabled by simply setting `l=1` immediately after line 255 in `code/train.py`. Is this correct or is there something else I additionally need to do?

**Comment by jiaaoc** [comment]
Yes, you could disable TMix by setting l=1.
