### ISSUE TITLE
original training and test data

### ISSUE THREAD

**Issue by eveliao** [GT-SALT/MixText#9]
Hi, could you please upload the data files of all datasets?

Besides, [pre-processed yahoo dataset](https://drive.google.com/file/d/1IoX9dp_RUHwIVA2_kJgHCWBOLHsV9V7A/view?usp=sharing) is not reachable now. Could you renew it? 

Thanks

**Comment by jiaaoc** [comment]
Hi, I think they could still be downloaded. I tested the link in the incognito mode.

For other datasets, it is easy to follow the provided commands/scripts to generate the training files.

Thanks.
